/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.SimpleCar;
import Business.Vehicle;
import Business.VehicleHistory;
import java.util.List;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lijianxi
 */
public class ViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPanel
     */
    private VehicleHistory vh;

    public ViewPanel(VehicleHistory vh) {
        initComponents();
        this.vh = vh;
        populateTable();
    }

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblViechle.getModel();
        dtm.setRowCount(0);

        for (Vehicle v : vh.getViechlehistory()) {
            Object row[] = new Object[11];
            row[0] = v;
            row[1] = v.getManufacturer();//getmanufacture
            row[2] = v.getModel();
            row[3] = v.getSeatnumber();
            row[4] = v.getManufactureyear();
            row[5] = v.getUpdatedate();
            row[6] = v.getExpiredDate();
            row[7] = v.getAvailable();
            row[8] = v.getCity();
            row[9] = v.getLatitue();
            row[10] = v.getLongitude();
            dtm.addRow(row);
        } //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViechle = new javax.swing.JTable();
        ExpDateTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        AvailableCheckBox = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        LatitudeTxt = new javax.swing.JTextField();
        ManufactureTxt = new javax.swing.JTextField();
        LongitudeTxt = new javax.swing.JTextField();
        ManuYearTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ModelTxt = new javax.swing.JTextField();
        SerialNumTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        SeatNumTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        UpdateDateTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        SearchSerialTxt = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        SelectModelNum = new javax.swing.JButton();
        SearchModelTxt = new javax.swing.JTextField();
        BtnAVANum = new javax.swing.JButton();
        txtAVA = new javax.swing.JTextField();
        txtNA = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        BtnListGivenYear = new javax.swing.JButton();
        txtGivenYear = new javax.swing.JTextField();
        BtnSeatNum = new javax.swing.JButton();
        txtMin = new javax.swing.JTextField();
        txtMax = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        BtnFindSerialNum = new javax.swing.JButton();
        BtnAllManufacture = new javax.swing.JButton();
        txtShowManus = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        ManuByBtn = new javax.swing.JButton();
        ManufacturerByTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        CityTxt = new javax.swing.JTextField();
        avaInCity = new javax.swing.JButton();
        GivenCityTxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblViechle2 = new javax.swing.JTable();
        BtnLastUpdate = new javax.swing.JButton();
        txtLastUpdate = new javax.swing.JTextField();
        ShowExpired = new javax.swing.JButton();
        RefreshBtn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        firstAvaBtn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        GPSLa = new javax.swing.JTextField();
        GPSLo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        jLabel1.setText("View ");

        tblViechle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Serial Num", "Manufacs", "Model", "SeatNum", "ManuYear", "UpdateDate", "ExpDate", "Available", "City", "Latitude", "Longitude"
            }
        ));
        jScrollPane1.setViewportView(tblViechle);

        jLabel5.setText("Serial Number");

        AvailableCheckBox.setText("Availabel");

        jLabel6.setText("Seat Number");

        jLabel9.setText("Latitude");

        jLabel7.setText("Updata Date");

        jLabel10.setText("Longitude");

        jLabel8.setText("Expired Date");

        ManufactureTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManufactureTxtActionPerformed(evt);
            }
        });

        LongitudeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LongitudeTxtActionPerformed(evt);
            }
        });

        ManuYearTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManuYearTxtActionPerformed(evt);
            }
        });

        jLabel11.setText("GPS Location");

        ModelTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModelTxtActionPerformed(evt);
            }
        });

        SerialNumTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SerialNumTxtActionPerformed(evt);
            }
        });

        jLabel2.setText("Manufacturer");

        jLabel3.setText("Model");

        jLabel4.setText("Manufactured Year");

        jButton1.setText("View Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel18.setText("serial num");

        SelectModelNum.setText(" Select Model ");
        SelectModelNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectModelNumActionPerformed(evt);
            }
        });

        BtnAVANum.setText("available num");
        BtnAVANum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAVANumActionPerformed(evt);
            }
        });

        txtNA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNAActionPerformed(evt);
            }
        });

        jLabel12.setText("AVA");

        jLabel13.setText("NA");

        BtnListGivenYear.setText("Manufacture year");
        BtnListGivenYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListGivenYearActionPerformed(evt);
            }
        });

        BtnSeatNum.setText("seat num&AVA");
        BtnSeatNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSeatNumActionPerformed(evt);
            }
        });

        txtMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaxActionPerformed(evt);
            }
        });

        jLabel16.setText("min");

        jLabel17.setText("max");

        BtnFindSerialNum.setText("find serial num");
        BtnFindSerialNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFindSerialNumActionPerformed(evt);
            }
        });

        BtnAllManufacture.setText("List all the manufacture ");
        BtnAllManufacture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAllManufactureActionPerformed(evt);
            }
        });

        txtShowManus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShowManusActionPerformed(evt);
            }
        });

        jLabel20.setText("Manufactures");

        ManuByBtn.setText("Manufactured By");
        ManuByBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManuByBtnActionPerformed(evt);
            }
        });

        jLabel14.setText("City");

        avaInCity.setText("List ava in");
        avaInCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avaInCityActionPerformed(evt);
            }
        });

        GivenCityTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GivenCityTxtActionPerformed(evt);
            }
        });

        tblViechle2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Serial Num", "Manufacs", "Model", "SeatNum", "ManuYear", "UpdateDate", "ExpDate", "Available", "City", "Latitude", "Longitude"
            }
        ));
        jScrollPane2.setViewportView(tblViechle2);

        BtnLastUpdate.setText("Last Update");
        BtnLastUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLastUpdateActionPerformed(evt);
            }
        });

        txtLastUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastUpdateActionPerformed(evt);
            }
        });

        ShowExpired.setText("Show Expired");
        ShowExpired.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowExpiredActionPerformed(evt);
            }
        });

        RefreshBtn.setText("Refresh");
        RefreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshBtnActionPerformed(evt);
            }
        });

        UpdateBtn.setText("UPDATE");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        firstAvaBtn.setText("First Avalb");
        firstAvaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstAvaBtnActionPerformed(evt);
            }
        });

        jLabel15.setText("Enter Your Location");

        jLabel19.setText("Latitude");

        jLabel21.setText("Longitude");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel14))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ManufactureTxt)
                                            .addComponent(ManuYearTxt)
                                            .addComponent(ModelTxt)
                                            .addComponent(SerialNumTxt)
                                            .addComponent(SeatNumTxt)
                                            .addComponent(UpdateDateTxt)
                                            .addComponent(ExpDateTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                            .addComponent(CityTxt)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(avaInCity)
                                        .addGap(18, 18, 18)
                                        .addComponent(GivenCityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addGap(15, 15, 15)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                            .addGap(37, 37, 37)
                                                            .addComponent(jLabel11)
                                                            .addGap(65, 65, 65))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGap(8, 8, 8)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(jLabel10)
                                                                .addComponent(jLabel9))
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(LatitudeTxt)
                                                                .addComponent(LongitudeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(UpdateBtn)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(RefreshBtn))
                                                            .addComponent(BtnAllManufacture))
                                                        .addGap(11, 11, 11))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jButton1)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jButton2)
                                                        .addGap(2, 2, 2))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(69, 69, 69)
                                                .addComponent(AvailableCheckBox)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(BtnAVANum)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel13)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(txtNA, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel12)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtAVA, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(BtnFindSerialNum)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel18))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(SelectModelNum)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(SearchModelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(ManuByBtn)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(ManufacturerByTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(BtnLastUpdate)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txtLastUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addComponent(ShowExpired))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addComponent(jLabel15)
                                                                .addGroup(layout.createSequentialGroup()
                                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel19)
                                                                        .addComponent(jLabel21))
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(GPSLo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                                                        .addComponent(GPSLa, javax.swing.GroupLayout.Alignment.TRAILING))))
                                                            .addComponent(firstAvaBtn)))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(BtnListGivenYear)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtGivenYear, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(SearchSerialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addGap(6, 6, 6)
                                                    .addComponent(BtnSeatNum)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel16)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtMin, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel17)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtMax, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtShowManus, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(429, 429, 429)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel12)
                                            .addComponent(txtAVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel13))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(txtNA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(BtnAVANum))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BtnListGivenYear)
                                    .addComponent(txtGivenYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(BtnSeatNum))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BtnFindSerialNum)
                                    .addComponent(SearchSerialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1)
                                    .addComponent(jButton2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(LatitudeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(LongitudeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AvailableCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RefreshBtn)
                                    .addComponent(UpdateBtn))))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnAllManufacture)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SelectModelNum)
                                .addComponent(SearchModelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ManufactureTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ManuYearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ModelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(SerialNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(SeatNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(UpdateDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(ExpDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtShowManus, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ManuByBtn)
                                    .addComponent(ManufacturerByTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BtnLastUpdate)
                                    .addComponent(txtLastUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addComponent(ShowExpired))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(CityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(avaInCity)
                                    .addComponent(GivenCityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GPSLa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GPSLo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(firstAvaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ManufactureTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManufactureTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManufactureTxtActionPerformed

    private void LongitudeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LongitudeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LongitudeTxtActionPerformed

    private void ManuYearTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManuYearTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManuYearTxtActionPerformed

    private void ModelTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModelTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModelTxtActionPerformed

    private void SerialNumTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SerialNumTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SerialNumTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selectedrow = tblViechle.getSelectedRow();
        if (selectedrow >= 0) {
            Vehicle v = (Vehicle) tblViechle.getValueAt(selectedrow, 0);
            ManufactureTxt.setText(v.getManufacturer());
            ManuYearTxt.setText(String.valueOf(v.getManufactureyear()));
            LongitudeTxt.setText(String.valueOf(v.getLongitude()));
            LatitudeTxt.setText(String.valueOf(v.getLatitue()));
            ModelTxt.setText(v.getModel());
            SeatNumTxt.setText(String.valueOf(v.getSeatnumber()));
            SerialNumTxt.setText(v.getSerialnumber());
            UpdateDateTxt.setText(v.getUpdatedate().toString());
            ExpDateTxt.setText(String.valueOf(v.getExpiredDate()));
            CityTxt.setText(v.getCity());
            AvailableCheckBox.setSelected(v.getAvailable());
            //How to set the AvailableCheckBox's Status

        } else {
            JOptionPane.showMessageDialog(null, "pls select any row.");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int selectedrow = tblViechle.getSelectedRow();

        if (selectedrow >= 0) {
            Vehicle v = (Vehicle) tblViechle.getValueAt(selectedrow, 0);
            vh.deleteViechle(v);
            JOptionPane.showMessageDialog(null, "Viehcle has been delete!");
            populateTable();
        } else {
            JOptionPane.showMessageDialog(null, "Please Select any row");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void SelectModelNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectModelNumActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) tblViechle2.getModel();
        dtm.setRowCount(0);
        String MODEL = SearchModelTxt.getText();

        for (Vehicle v : vh.getViechlehistory()) {
            if (v.getModel().equals(MODEL)) {
                Object row[] = new Object[11];
                row[0] = v;
                row[1] = v.getManufacturer();//getmanufacture
                row[2] = v.getModel();
                row[3] = v.getSeatnumber();
                row[4] = v.getManufactureyear();
                row[5] = v.getUpdatedate();
                row[6] = v.getExpiredDate();
                row[7] = v.getAvailable();
                row[8] = v.getCity();
                row[9] = v.getLatitue();
                row[10] = v.getLongitude();
                dtm.addRow(row);
            }
        }

    }//GEN-LAST:event_SelectModelNumActionPerformed

    private void BtnAVANumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAVANumActionPerformed
        int i;
        int avanum = 0;
        int NAnum = 0;
        for (i = 0; i < tblViechle.getRowCount(); i++) {
            Vehicle v = (Vehicle) tblViechle.getValueAt(i, 0);
            boolean ava = v.getAvailable();
            if (ava == true) {
                avanum++;
            }
        }
        for (i = 0; i < tblViechle.getRowCount(); i++) {
            Vehicle v = (Vehicle) tblViechle.getValueAt(i, 0);
            boolean ava = v.getAvailable();
            if (ava == false) {
                NAnum++;
            }
        }

        txtAVA.setText(String.valueOf(avanum));
        txtNA.setText(String.valueOf(NAnum));

    }//GEN-LAST:event_BtnAVANumActionPerformed

    private void txtNAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNAActionPerformed

    private void BtnListGivenYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListGivenYearActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) tblViechle2.getModel();
        dtm.setRowCount(0);
        int MANUYEAR = Integer.parseInt(txtGivenYear.getText());

        for (Vehicle v : vh.getViechlehistory()) {
            if (v.getManufactureyear() == MANUYEAR) {
                Object row[] = new Object[11];
                row[0] = v;
                row[1] = v.getManufacturer();//getmanufacture
                row[2] = v.getModel();
                row[3] = v.getSeatnumber();
                row[4] = v.getManufactureyear();
                row[5] = v.getUpdatedate();
                row[6] = v.getExpiredDate();
                row[7] = v.getAvailable();
                row[8] = v.getCity();
                row[9] = v.getLatitue();
                row[10] = v.getLongitude();
                dtm.addRow(row);
            }
        }

    }//GEN-LAST:event_BtnListGivenYearActionPerformed

    private void BtnSeatNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSeatNumActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) tblViechle2.getModel();
        dtm.setRowCount(0);
        int minseat = Integer.parseInt(txtMin.getText());
        int maxseat = Integer.parseInt(txtMax.getText());

        for (Vehicle v : vh.getViechlehistory()) {
            if (v.getSeatnumber() >= minseat && v.getSeatnumber() <= maxseat) {
                Object row[] = new Object[11];
                row[0] = v;
                row[1] = v.getManufacturer();//getmanufacture
                row[2] = v.getModel();
                row[3] = v.getSeatnumber();
                row[4] = v.getManufactureyear();
                row[5] = v.getUpdatedate();
                row[6] = v.getExpiredDate();
                row[7] = v.getAvailable();
                row[8] = v.getCity();
                row[9] = v.getLatitue();
                row[10] = v.getLongitude();
                dtm.addRow(row);
            }
        }
    }//GEN-LAST:event_BtnSeatNumActionPerformed

    private void txtMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaxActionPerformed

    private void BtnFindSerialNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFindSerialNumActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) tblViechle2.getModel();
        dtm.setRowCount(0);
        String SERIALNUM = SearchSerialTxt.getText();

        for (Vehicle v : vh.getViechlehistory()) {
            if (v.getSerialnumber().equals(SERIALNUM)) {
                Object row[] = new Object[11];
                row[0] = v;
                row[1] = v.getManufacturer();//getmanufacture
                row[2] = v.getModel();
                row[3] = v.getSeatnumber();
                row[4] = v.getManufactureyear();
                row[5] = v.getUpdatedate();
                row[6] = v.getExpiredDate();
                row[7] = v.getAvailable();
                row[8] = v.getCity();
                row[9] = v.getLatitue();
                row[10] = v.getLongitude();
                dtm.addRow(row);
            }
        }

    }//GEN-LAST:event_BtnFindSerialNumActionPerformed

    private void BtnAllManufactureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAllManufactureActionPerformed
        // TODO add your handling code here:
        List<String> manus = new ArrayList<String>();
        vh.getViechlehistory().forEach((v) -> {
            manus.add(v.getManufacturer());
        });
        Set<String> uniquemanus = new HashSet<String>(manus);

        int i;
        Object[] obj = uniquemanus.toArray();
        StringBuilder sb = new StringBuilder();
        txtShowManus.setText(Arrays.toString(obj));
        /*for (i=0; i<uniquemanus.size(); i++)
        {

        }  */

    }//GEN-LAST:event_BtnAllManufactureActionPerformed

    private void txtShowManusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShowManusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtShowManusActionPerformed

    private void ManuByBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManuByBtnActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) tblViechle2.getModel();
        dtm.setRowCount(0);
        String MANUBY = ManufacturerByTxt.getText();

        for (Vehicle v : vh.getViechlehistory()) {
            if (v.getManufacturer().equals(MANUBY)) {
                Object row[] = new Object[11];
                row[0] = v;
                row[1] = v.getManufacturer();//getmanufacture
                row[2] = v.getModel();
                row[3] = v.getSeatnumber();
                row[4] = v.getManufactureyear();
                row[5] = v.getUpdatedate();
                row[6] = v.getExpiredDate();
                row[7] = v.getAvailable();
                row[8] = v.getCity();
                row[9] = v.getLatitue();
                row[10] = v.getLongitude();
                dtm.addRow(row);
            }
        }
    }//GEN-LAST:event_ManuByBtnActionPerformed

    private void GivenCityTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GivenCityTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GivenCityTxtActionPerformed

    private void avaInCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avaInCityActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) tblViechle2.getModel();
        dtm.setRowCount(0);
        String GivenCity = GivenCityTxt.getText();

        for (Vehicle v : vh.getViechlehistory()) {
            if (v.getCity().equals(GivenCity) && v.getAvailable() == true) {
                Object row[] = new Object[11];
                row[0] = v;
                row[1] = v.getManufacturer();//getmanufacture
                row[2] = v.getModel();
                row[3] = v.getSeatnumber();
                row[4] = v.getManufactureyear();
                row[5] = v.getUpdatedate();
                row[6] = v.getExpiredDate();
                row[7] = v.getAvailable();
                row[8] = v.getCity();
                row[9] = v.getLatitue();
                row[10] = v.getLongitude();
                dtm.addRow(row);
            }
        }
    }//GEN-LAST:event_avaInCityActionPerformed

    private void BtnLastUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLastUpdateActionPerformed
        // TODO add your handling code here:     
        int i;
        Vehicle fff = (Vehicle) tblViechle.getValueAt(0, 0);
        Date oridate = fff.getUpdatedate();//to create an oriday
        for (i = 0; i < tblViechle.getRowCount(); i++) {
            Vehicle v1 = (Vehicle) tblViechle.getValueAt(i, 0);
            Date lastupdatedate = v1.getUpdatedate();
            //get the updatedate from the arraylist
            // it will refresh everytime

            if (lastupdatedate.after(oridate)) {
                oridate = lastupdatedate;
            }
        }
        DateFormat df = new SimpleDateFormat("MM/dd/yyyy");
        String strupdatedate = df.format(oridate);
        txtLastUpdate.setText(strupdatedate);

    }//GEN-LAST:event_BtnLastUpdateActionPerformed

    private void txtLastUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastUpdateActionPerformed

    private void ShowExpiredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowExpiredActionPerformed
        Date today = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Calendar c1 = Calendar.getInstance();
        c1.setTime(today);
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) tblViechle2.getModel();
        dtm.setRowCount(0);
        for (Vehicle v : vh.getViechlehistory()) {
            Date expiredate = v.getExpiredDate();
            Calendar c2 = Calendar.getInstance();
            c2.setTime(expiredate);
            if (c2.before(c1)) {
                Object row[] = new Object[11];
                row[0] = v;
                row[1] = v.getManufacturer();//getmanufacture
                row[2] = v.getModel();
                row[3] = v.getSeatnumber();
                row[4] = v.getManufactureyear();
                row[5] = v.getUpdatedate();
                row[6] = v.getExpiredDate();
                row[7] = v.getAvailable();
                row[8] = v.getCity();
                row[9] = v.getLatitue();
                row[10] = v.getLongitude();
                dtm.addRow(row);
            }
        }

    }//GEN-LAST:event_ShowExpiredActionPerformed

    private void RefreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshBtnActionPerformed
        this.populateTable();        // TODO add your handling code here:
    }//GEN-LAST:event_RefreshBtnActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        int selectedrow = tblViechle.getSelectedRow();
        if (selectedrow >= 0) {
            Vehicle v0 = (Vehicle) tblViechle.getValueAt(selectedrow, 0);
            String manufacture = ManufactureTxt.getText();
            int manuYear = Integer.parseInt(ManuYearTxt.getText());
            int seatNum = Integer.parseInt(SeatNumTxt.getText());
            String SerialNum = SerialNumTxt.getText();
            String modle = ModelTxt.getText();
            String updatedate = UpdateDateTxt.getText();
            String ExpDate = ExpDateTxt.getText();
            Boolean available = AvailableCheckBox.isSelected();
            Double latitude = Double.parseDouble(LatitudeTxt.getText());
            Double longitude = Double.parseDouble(LongitudeTxt.getText());
            String city = CityTxt.getText();
            //AvailableCheckBox
            v0.setManufacturer(manufacture);
            v0.setManufactureyear(manuYear);
            v0.setSeatnumber(seatNum);
            v0.setSerialnumber(SerialNum);
            v0.setModel(modle);
            try {
                //v1.setUpdatedate(updatedate);
                v0.setUpdatedate(updatedate);
            } catch (ParseException ex) {
                Logger.getLogger(CreateJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                v0.setExpiredDate(ExpDate);
            } catch (ParseException ex) {
                Logger.getLogger(CreateJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            v0.setAvailable(available);
            v0.setLatitue(latitude);
            v0.setLongitude(longitude);
            v0.setCity(city);

            DefaultTableModel dtm = (DefaultTableModel) tblViechle.getModel();
            dtm.setRowCount(0);

            for (Vehicle v : vh.getViechlehistory()) {
                Object row[] = new Object[11];
                row[0] = v;
                row[1] = v.getManufacturer();//getmanufacture
                row[2] = v.getModel();
                row[3] = v.getSeatnumber();
                row[4] = v.getManufactureyear();
                row[5] = v.getUpdatedate();
                row[6] = v.getExpiredDate();
                row[7] = v.getAvailable();
                row[8] = v.getCity();
                row[9] = v.getLatitue();
                row[10] = v.getLongitude();
                dtm.addRow(row);
            } //To change body of generated methods, choose Tools | Templates.

            this.clearAllTextField();
        } else {
            JOptionPane.showMessageDialog(null, "pls select any row.");
        }

    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void firstAvaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstAvaBtnActionPerformed

        //Calculate the minimum distance and find which one is the closet and also availabel
        double my_lo = Double.parseDouble(GPSLo.getText());
        double my_la = Double.parseDouble(GPSLa.getText());
        List<SimpleCar> dis = new ArrayList();

        for (Vehicle v : vh.getViechlehistory()) {
            double vla = v.getLatitue();
            double vlo = v.getLongitude();
            SimpleCar sc = new SimpleCar();
            double distance = Math.sqrt(Math.pow((vlo - my_lo), 2) + Math.pow((vla - my_la), 2));
            String serialnum = v.getSerialnumber();
            boolean available = v.getAvailable();
            sc.setSerialnum(serialnum);
            sc.setAvailable(available);
            sc.setDistance(distance);
            dis.add(sc);
        }
////   
        Collections.sort(dis, new Comparator<SimpleCar>() {
            @Override
            public int compare(SimpleCar o1, SimpleCar o2) {
                double s1dis = o1.getDistance();
                double s2dis = o2.getDistance();
                if (s1dis > s2dis) {
                    return 1;
                } else if (s1dis < s2dis) {
                    return -1;
                } else {
                    return 0;
                }
            }
        });

        String scNum = null;
        for (SimpleCar sc1 : dis) {
            if (sc1.isAvailable() == true) {
                scNum = sc1.getSerialnum();
                break;
            }
        }

        DefaultTableModel dtm = (DefaultTableModel) tblViechle2.getModel();
        dtm.setRowCount(0);
        String MANUBY = ManufacturerByTxt.getText();

        for (Vehicle v : vh.getViechlehistory()) {
            if (v.getSerialnumber().equals(scNum)) {
                Object row[] = new Object[11];
                row[0] = v;
                row[1] = v.getManufacturer();//getmanufacture
                row[2] = v.getModel();
                row[3] = v.getSeatnumber();
                row[4] = v.getManufactureyear();
                row[5] = v.getUpdatedate();
                row[6] = v.getExpiredDate();
                row[7] = v.getAvailable();
                row[8] = v.getCity();
                row[9] = v.getLatitue();
                row[10] = v.getLongitude();
                dtm.addRow(row);
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_firstAvaBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AvailableCheckBox;
    private javax.swing.JButton BtnAVANum;
    private javax.swing.JButton BtnAllManufacture;
    private javax.swing.JButton BtnFindSerialNum;
    private javax.swing.JButton BtnLastUpdate;
    private javax.swing.JButton BtnListGivenYear;
    private javax.swing.JButton BtnSeatNum;
    private javax.swing.JTextField CityTxt;
    private javax.swing.JTextField ExpDateTxt;
    private javax.swing.JTextField GPSLa;
    private javax.swing.JTextField GPSLo;
    private javax.swing.JTextField GivenCityTxt;
    private javax.swing.JTextField LatitudeTxt;
    private javax.swing.JTextField LongitudeTxt;
    private javax.swing.JButton ManuByBtn;
    private javax.swing.JTextField ManuYearTxt;
    private javax.swing.JTextField ManufactureTxt;
    private javax.swing.JTextField ManufacturerByTxt;
    private javax.swing.JTextField ModelTxt;
    private javax.swing.JButton RefreshBtn;
    private javax.swing.JTextField SearchModelTxt;
    private javax.swing.JTextField SearchSerialTxt;
    private javax.swing.JTextField SeatNumTxt;
    private javax.swing.JButton SelectModelNum;
    private javax.swing.JTextField SerialNumTxt;
    private javax.swing.JButton ShowExpired;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JTextField UpdateDateTxt;
    private javax.swing.JButton avaInCity;
    private javax.swing.JButton firstAvaBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblViechle;
    private javax.swing.JTable tblViechle2;
    private javax.swing.JTextField txtAVA;
    private javax.swing.JTextField txtGivenYear;
    private javax.swing.JTextField txtLastUpdate;
    private javax.swing.JTextField txtMax;
    private javax.swing.JTextField txtMin;
    private javax.swing.JTextField txtNA;
    private javax.swing.JTextField txtShowManus;
    // End of variables declaration//GEN-END:variables

    private void clearAllTextField() {
        ManufactureTxt.setText("");
        ManuYearTxt.setText("");
        SeatNumTxt.setText("");
        SerialNumTxt.setText("");
        ModelTxt.setText("");
        UpdateDateTxt.setText("");
        ExpDateTxt.setText("");
        //AvailableCheckBox.setText("");
        LatitudeTxt.setText("");
        LongitudeTxt.setText("");
        CityTxt.setText(""); //To change body of generated methods, choose Tools | Templates.
    }

}
