/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Business.FlightHistory;
import static java.lang.String.valueOf;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Collections;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author lijianxi
 */

public class ViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPanel
     */
    private FlightHistory fh;
    public ViewPanel(FlightHistory fh) {
        initComponents();
        this.fh=fh;
        populateTable();
    }
    
    public void populateTable()
    {
        DefaultTableModel dtm=(DefaultTableModel)tblFlight.getModel();
        dtm.setRowCount(0);
        
        for(Flight fl:fh.getFlightHistory())
        {
            Object row[]=new Object[11];
            row[0]=fl;//the object
            row[1]=fl.getFlighttime();
            row[2]=fl.getAirplane().getSerialnumber();
            row[3]=fl.getAirplane().getAvalable();
            row[4]=fl.getAirplane().getManufacturer();
            row[5]=fl.getAirplane().getManufactureyear();
            row[6]=fl.getAirplane().getModelnumber();
            row[7]=fl.getAirplane().getSeatnumber();
            row[8]=fl.getAirplane().getUpdatedate();
            row[9]=fl.getAirplane().getExpired();
            row[10]=fl.getAirplane().getAirliner();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFlight = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnViewDetails = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        AirlinerTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        SerialNumTextField = new javax.swing.JTextField();
        SeatsTextField = new javax.swing.JTextField();
        UDTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ManuTextField = new javax.swing.JTextField();
        ManuYearTextField = new javax.swing.JTextField();
        ModelNumTextField = new javax.swing.JTextField();
        FlightTimeTextField = new javax.swing.JTextField();
        AirportTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        AVATextField = new javax.swing.JTextField();
        EXPTextField = new javax.swing.JTextField();
        BtnFirstAVA = new javax.swing.JButton();
        BtnAVANum = new javax.swing.JButton();
        txtAVA = new javax.swing.JTextField();
        txtNA = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        BtnBoeing = new javax.swing.JButton();
        BtnListGivenYear = new javax.swing.JButton();
        txtGivenYear = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        BtnSeatNum = new javax.swing.JButton();
        txtMin = new javax.swing.JTextField();
        txtMax = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        BtnFindSerialNum = new javax.swing.JButton();
        SearchSerialTxt = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        SelectModelNum = new javax.swing.JButton();
        SearchModelTxt = new javax.swing.JTextField();
        BtnViewAll = new javax.swing.JButton();
        BtnShowExpired = new javax.swing.JButton();
        AVAILABLE = new javax.swing.JButton();
        txtAVAairport = new javax.swing.JTextField();
        BtnLastUpdate = new javax.swing.JButton();
        txtLastUpdate = new javax.swing.JTextField();
        BtnAllManufacture = new javax.swing.JButton();
        txtSelectAl = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtShowManus = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();

        tblFlight.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Airport", "FlightTime", "Serial Num", "Avalable", "Manufacturer", "ManuYear", "ModelNum", "Seats", "UpdateDate", "Expired", "Airliner"
            }
        ));
        jScrollPane1.setViewportView(tblFlight);

        jLabel2.setText("View Flight History");

        btnViewDetails.setText("view details");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        btnDelete.setText("delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        UpdateBtn.setText("UPDATE");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        jButton4.setText("search");

        jLabel9.setText("Airliner");

        AirlinerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AirlinerTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Manufacturer");

        jLabel3.setText("Manufacture Year");

        jLabel4.setText("Model Num");

        jLabel5.setText("Serial Num");

        jLabel6.setText("Seats");

        jLabel13.setText("Update Date");

        ManuTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManuTextFieldActionPerformed(evt);
            }
        });

        ManuYearTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManuYearTextFieldActionPerformed(evt);
            }
        });

        ModelNumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModelNumTextFieldActionPerformed(evt);
            }
        });

        jLabel14.setText("Airport");

        jLabel10.setText("FlightTime");

        jLabel12.setText("Avalable");

        jLabel8.setText("Expired");

        BtnFirstAVA.setText("Firtst available");
        BtnFirstAVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFirstAVAActionPerformed(evt);
            }
        });

        BtnAVANum.setText("available num");
        BtnAVANum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAVANumActionPerformed(evt);
            }
        });

        txtNA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNAActionPerformed(evt);
            }
        });

        jLabel7.setText("AVA");

        jLabel11.setText("NA");

        BtnBoeing.setText("show boeing");
        BtnBoeing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBoeingActionPerformed(evt);
            }
        });

        BtnListGivenYear.setText("Manufacture year");
        BtnListGivenYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListGivenYearActionPerformed(evt);
            }
        });

        BtnSeatNum.setText("seat num&AVA");
        BtnSeatNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSeatNumActionPerformed(evt);
            }
        });

        txtMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaxActionPerformed(evt);
            }
        });

        jLabel16.setText("min");

        jLabel17.setText("max");

        BtnFindSerialNum.setText("find serial num");
        BtnFindSerialNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFindSerialNumActionPerformed(evt);
            }
        });

        jLabel18.setText("serial num");

        SelectModelNum.setText(" Select Model num");
        SelectModelNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectModelNumActionPerformed(evt);
            }
        });

        BtnViewAll.setText("View all");
        BtnViewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewAllActionPerformed(evt);
            }
        });

        BtnShowExpired.setText("ShowExpired");
        BtnShowExpired.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnShowExpiredActionPerformed(evt);
            }
        });

        AVAILABLE.setText(" AVA @ Airport");
        AVAILABLE.setToolTipText("");
        AVAILABLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AVAILABLEActionPerformed(evt);
            }
        });

        txtAVAairport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAVAairportActionPerformed(evt);
            }
        });

        BtnLastUpdate.setText("Last Update");
        BtnLastUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLastUpdateActionPerformed(evt);
            }
        });

        txtLastUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastUpdateActionPerformed(evt);
            }
        });

        BtnAllManufacture.setText("List all the manufacture ");
        BtnAllManufacture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAllManufactureActionPerformed(evt);
            }
        });

        txtSelectAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSelectAlActionPerformed(evt);
            }
        });

        jLabel19.setText("Enter the Airliner");

        txtShowManus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShowManusActionPerformed(evt);
            }
        });

        jLabel20.setText("Manufactures");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel8)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ManuTextField)
                                    .addComponent(AirlinerTextField)
                                    .addComponent(ManuYearTextField)
                                    .addComponent(ModelNumTextField)
                                    .addComponent(SerialNumTextField)
                                    .addComponent(SeatsTextField)
                                    .addComponent(UDTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(EXPTextField))
                                .addGap(55, 55, 55)
                                .addComponent(btnViewDetails)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDelete))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(292, 292, 292)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(UpdateBtn)
                                                .addGap(33, 33, 33)
                                                .addComponent(jButton4))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel10)
                                                        .addComponent(jLabel14))
                                                    .addComponent(jLabel12))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(AirportTextField)
                                                    .addComponent(AVATextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(FlightTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(jLabel20)
                                                .addGap(37, 37, 37)
                                                .addComponent(txtShowManus, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(BtnAllManufacture)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel19)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtSelectAl))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(307, 307, 307)
                                .addComponent(BtnViewAll)
                                .addGap(59, 59, 59))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(BtnAVANum)
                                                .addComponent(BtnBoeing))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel11)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(txtNA, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel7)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtAVA, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(BtnListGivenYear)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel15)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtGivenYear, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(BtnSeatNum)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel16)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtMin, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel17)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtMax, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(8, 8, 8)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(6, 6, 6)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(BtnShowExpired)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(AVAILABLE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(txtAVAairport, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(BtnLastUpdate)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(txtLastUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(BtnFindSerialNum)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel18)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(SearchSerialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(SelectModelNum)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(SearchModelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BtnFirstAVA)
                                        .addGap(238, 238, 238)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 44, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(BtnViewAll)
                        .addGap(5, 5, 5)
                        .addComponent(BtnFirstAVA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtAVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(txtNA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnAVANum)
                                .addGap(20, 20, 20)
                                .addComponent(BtnBoeing)
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BtnListGivenYear)
                                    .addComponent(txtGivenYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16)
                                .addComponent(jLabel17))
                            .addComponent(BtnSeatNum))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnFindSerialNum)
                            .addComponent(SearchSerialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SelectModelNum)
                            .addComponent(SearchModelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnShowExpired)
                            .addComponent(BtnAllManufacture))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AVAILABLE)
                                    .addComponent(txtAVAairport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BtnLastUpdate)
                                    .addComponent(txtLastUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(txtSelectAl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(txtShowManus, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel9)
                                            .addComponent(AirlinerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(56, 56, 56))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(ManuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1))
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(ManuYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(ModelNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(SerialNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(SeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(UDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnViewDetails)
                                            .addComponent(btnDelete))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel14)
                                            .addComponent(AirportTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel10)
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel12)
                                            .addComponent(AVATextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(102, 102, 102)
                                        .addComponent(FlightTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(UpdateBtn)
                                    .addComponent(jButton4))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 468, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(EXPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedrow= tblFlight.getSelectedRow();
        
        
              if(selectedrow>=0)
        {
          Flight vs=(Flight)tblFlight.getValueAt(selectedrow, 0);
          fh.deleteFlight(vs);
          JOptionPane.showMessageDialog(null, "Vital Sign has been delete!");
          populateTable();
        }
        else 
            JOptionPane.showMessageDialog(null, "Please Select any row");

        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void AirlinerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AirlinerTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AirlinerTextFieldActionPerformed

    private void ManuTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManuTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManuTextFieldActionPerformed

    private void ManuYearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManuYearTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManuYearTextFieldActionPerformed

    private void ModelNumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModelNumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModelNumTextFieldActionPerformed

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        
        int selectedrow=tblFlight.getSelectedRow();
        if(selectedrow>=0)
        {
            Flight fl=(Flight)tblFlight.getValueAt(selectedrow, 0);
            AirlinerTextField.setText(fl.getAirplane().getAirliner());
            AirportTextField.setText(fl.getAirport());
            SimpleDateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
            //updatedate
            UDTextField.setText(formatter.format(fl.getAirplane().getUpdatedate()));
            
             DateFormat df = new SimpleDateFormat("MM/dd/yyyy  HH:mm");
            FlightTimeTextField.setText(df.format(fl.getFlighttime()));
            AVATextField.setText(fl.getAirplane().getAvalable());
            ManuYearTextField.setText(String.valueOf(fl.getAirplane().getManufactureyear()));
            ModelNumTextField.setText(fl.getAirplane().getModelnumber());
            SeatsTextField.setText(String.valueOf(fl.getAirplane().getSeatnumber()));
            SerialNumTextField.setText(String.valueOf(fl.getAirplane().getSerialnumber()));
            ManuTextField.setText(fl.getAirplane().getManufacturer());
            EXPTextField.setText(fl.getAirplane().getExpired());
          
        }
        else
            JOptionPane.showMessageDialog(null, "pls select any row.");

        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        // TODO add your handling code here:

        
       int selectedrow=tblFlight.getSelectedRow();
       //get the index FROM tblFlight same as Flight History
       
       
        if(selectedrow>=0)
        {
         Flight fl=(Flight)tblFlight.getValueAt(selectedrow, 0);
         String airliner =AirlinerTextField.getText();
         String manuf= ManuTextField.getText();
         int manuyear=Integer.parseInt( ManuYearTextField.getText());
         String modelnum= ModelNumTextField.getText();
         int serialnum=Integer.parseInt(SerialNumTextField.getText());
         String flighttime=FlightTimeTextField.getText();
         String updatedate=UDTextField.getText();
         String expdate=EXPTextField.getText();
         String ava=AVATextField.getText();
         String airport=AirportTextField.getText();
         int seats= Integer.parseInt(SeatsTextField.getText());
         //get all the information from the textfield;
         //how to access the obj in the arraylist
        
        
         fl.setAirport(airport);
           try {
               fl.setFlighttime(flighttime);
           } catch (ParseException ex) {
               Logger.getLogger(ViewPanel.class.getName()).log(Level.SEVERE, null, ex);
           }
         fl.getAirplane().setAirliner(airliner);
         fl.getAirplane().setExpired(expdate);
         fl.getAirplane().setAvalable(ava);
         fl.getAirplane().setManufacturer(manuf);
         fl.getAirplane().setManufactureyear(manuyear);
         fl.getAirplane().setModelnumber(modelnum);
         fl.getAirplane().setSeatnumber(seats);
         fl.getAirplane().setSerialnumber(serialnum);
           try {
               fl.getAirplane().setUpdatedate(updatedate);
               //send the valeus to the new object;
               //how to change the old obj in arraylist to the new ???
           } catch (ParseException ex) {
               Logger.getLogger(ViewPanel.class.getName()).log(Level.SEVERE, null, ex);
           }
        
         
         JOptionPane.showMessageDialog(null, "Flight Updated Successsfully");
         
         AirlinerTextField.setText("");
         ManuTextField.setText("");
         ManuYearTextField.setText("");
         ModelNumTextField.setText("");
         SerialNumTextField.setText("");
         FlightTimeTextField.setText("");
         UDTextField.setText("");
         AVATextField.setText("");
         AirportTextField.setText("");
         SeatsTextField.setText("");
         EXPTextField.setText("");
         
         //And the refresh the table;
            
           
         tblFlight.repaint();
        }
        else
            JOptionPane.showMessageDialog(null, "pls select any row.");
        
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void txtNAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNAActionPerformed

    private void txtMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaxActionPerformed

    private void SelectModelNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectModelNumActionPerformed
        // TODO add your handling code here:
         DefaultTableModel dtm=(DefaultTableModel)tblFlight.getModel();
        dtm.setRowCount(0);
        int MODEL=Integer.parseInt( SearchModelTxt.getText());
        
        for(Flight fl:fh.getFlightHistory())
        {
            if(Integer.parseInt(fl.getAirplane().getModelnumber())==MODEL)
            {
            Object row[]=new Object[11];
            row[0]=fl;//the object
            row[1]=fl.getFlighttime();
            row[2]=fl.getAirplane().getSerialnumber();
            row[3]=fl.getAirplane().getAvalable();
            row[4]=fl.getAirplane().getManufacturer();
            row[5]=fl.getAirplane().getManufactureyear();
            row[6]=fl.getAirplane().getModelnumber();
            row[7]=fl.getAirplane().getSeatnumber();
            row[8]=fl.getAirplane().getUpdatedate();
            row[9]=fl.getAirplane().getExpired();
            row[10]=fl.getAirplane().getAirliner();
            dtm.addRow(row);
            }
        }
        
        
    }//GEN-LAST:event_SelectModelNumActionPerformed

    private void BtnFirstAVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFirstAVAActionPerformed
        // TODO add your handling code here:
        
        List<Date> dates = new ArrayList<Date>();
        Date nndate= new Date();
          for(Flight fl:fh.getFlightHistory())
          {  if(fl.getFlighttime().after(nndate))
            {
              dates.add(fl.getFlighttime());
            }
          }
        Date latest = Collections.min(dates);
        
        
        
        DefaultTableModel dtm=(DefaultTableModel)tblFlight.getModel();
        dtm.setRowCount(0);
      
        for(Flight fl:fh.getFlightHistory())
        {
            if(fl.getFlighttime()==latest)
            {
            Object row[]=new Object[11];
            row[0]=fl;//the object
            row[1]=fl.getFlighttime();
            row[2]=fl.getAirplane().getSerialnumber();
            row[3]=fl.getAirplane().getAvalable();
            row[4]=fl.getAirplane().getManufacturer();
            row[5]=fl.getAirplane().getManufactureyear();
            row[6]=fl.getAirplane().getModelnumber();
            row[7]=fl.getAirplane().getSeatnumber();
            row[8]=fl.getAirplane().getUpdatedate();
            row[9]=fl.getAirplane().getExpired();
            row[10]=fl.getAirplane().getAirliner();
            dtm.addRow(row);
            }
        }  
    }//GEN-LAST:event_BtnFirstAVAActionPerformed

    private void BtnViewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewAllActionPerformed
        // TODO add your handling code here:
         DefaultTableModel dtm=(DefaultTableModel)tblFlight.getModel();
        dtm.setRowCount(0);
        
        for(Flight fl:fh.getFlightHistory())
        {
            Object row[]=new Object[11];
            row[0]=fl;//the object
            row[1]=fl.getFlighttime();
            row[2]=fl.getAirplane().getSerialnumber();
            row[3]=fl.getAirplane().getAvalable();
            row[4]=fl.getAirplane().getManufacturer();
            row[5]=fl.getAirplane().getManufactureyear();
            row[6]=fl.getAirplane().getModelnumber();
            row[7]=fl.getAirplane().getSeatnumber();
            row[8]=fl.getAirplane().getUpdatedate();
            row[9]=fl.getAirplane().getExpired();
            row[10]=fl.getAirplane().getAirliner();
            dtm.addRow(row);
        }
        
    }//GEN-LAST:event_BtnViewAllActionPerformed

    private void BtnAVANumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAVANumActionPerformed
        int i;
        int avanum=0;
        int NAnum = 0;
       for(i=0;i<tblFlight.getRowCount();i++)
       {
        Flight fl=(Flight)tblFlight.getValueAt(i, 0);
        String ava = fl.getAirplane().getAvalable();
        if (ava.equals("AVAILABLE"))
        {
            avanum++;
        }
       }
       for(i=0;i<tblFlight.getRowCount();i++)
       {
        Flight fl=(Flight)tblFlight.getValueAt(i, 0);
        String ava = fl.getAirplane().getAvalable();
        if (ava.equals("UNAVA"))
        {
            NAnum++;
        }
       }
  
       txtAVA.setText(String.valueOf(avanum));
       txtNA.setText(String.valueOf(NAnum));
       
       
    }//GEN-LAST:event_BtnAVANumActionPerformed

    private void BtnBoeingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBoeingActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel dtm=(DefaultTableModel)tblFlight.getModel();
        dtm.setRowCount(0);
        
        for(Flight fl:fh.getFlightHistory())
        {
            if(fl.getAirplane().getManufacturer().equals("Boeing"))
            {
            Object row[]=new Object[11];
            row[0]=fl;//the object
            row[1]=fl.getFlighttime();
            row[2]=fl.getAirplane().getSerialnumber();
            row[3]=fl.getAirplane().getAvalable();
            row[4]=fl.getAirplane().getManufacturer();
            row[5]=fl.getAirplane().getManufactureyear();
            row[6]=fl.getAirplane().getModelnumber();
            row[7]=fl.getAirplane().getSeatnumber();
            row[8]=fl.getAirplane().getUpdatedate();
            row[9]=fl.getAirplane().getExpired();
            row[10]=fl.getAirplane().getAirliner();
            dtm.addRow(row);
            }
        }
    }//GEN-LAST:event_BtnBoeingActionPerformed

    private void BtnListGivenYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListGivenYearActionPerformed
        // TODO add your handling code here:
         DefaultTableModel dtm=(DefaultTableModel)tblFlight.getModel();
        dtm.setRowCount(0);
        int MANUYEAR=Integer.parseInt( txtGivenYear.getText());
        
        for(Flight fl:fh.getFlightHistory())
        {
            if(fl.getAirplane().getManufactureyear()==MANUYEAR)
            {
            Object row[]=new Object[11];
            row[0]=fl;//the object
            row[1]=fl.getFlighttime();
            row[2]=fl.getAirplane().getSerialnumber();
            row[3]=fl.getAirplane().getAvalable();
            row[4]=fl.getAirplane().getManufacturer();
            row[5]=fl.getAirplane().getManufactureyear();
            row[6]=fl.getAirplane().getModelnumber();
            row[7]=fl.getAirplane().getSeatnumber();
            row[8]=fl.getAirplane().getUpdatedate();
            row[9]=fl.getAirplane().getExpired();
            row[10]=fl.getAirplane().getAirliner();
            dtm.addRow(row);
            }
        }
        
    }//GEN-LAST:event_BtnListGivenYearActionPerformed

    private void BtnSeatNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSeatNumActionPerformed
        // TODO add your handling code here:
         DefaultTableModel dtm=(DefaultTableModel)tblFlight.getModel();
        dtm.setRowCount(0);
        int minseat=Integer.parseInt( txtMin.getText());
        int maxseat=Integer.parseInt( txtMax.getText());
        
        
        for(Flight fl:fh.getFlightHistory())
        {
            if(fl.getAirplane().getSeatnumber()>=minseat && fl.getAirplane().getSeatnumber()<=maxseat&& fl.getAirplane().getAvalable().equals("AVAILABLE"))
            {
            Object row[]=new Object[11];
            row[0]=fl;//the object
            row[1]=fl.getFlighttime();
            row[2]=fl.getAirplane().getSerialnumber();
            row[3]=fl.getAirplane().getAvalable();
            row[4]=fl.getAirplane().getManufacturer();
            row[5]=fl.getAirplane().getManufactureyear();
            row[6]=fl.getAirplane().getModelnumber();
            row[7]=fl.getAirplane().getSeatnumber();
            row[8]=fl.getAirplane().getUpdatedate();
            row[9]=fl.getAirplane().getExpired();
            row[10]=fl.getAirplane().getAirliner();
            dtm.addRow(row);
            }
        }
    }//GEN-LAST:event_BtnSeatNumActionPerformed

    private void BtnFindSerialNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFindSerialNumActionPerformed
        // TODO add your handling code here:
         DefaultTableModel dtm=(DefaultTableModel)tblFlight.getModel();
        dtm.setRowCount(0);
        int SERIALNUM=Integer.parseInt( SearchSerialTxt.getText());
        
        for(Flight fl:fh.getFlightHistory())
        {
            if(fl.getAirplane().getSerialnumber()==SERIALNUM)
            {
            Object row[]=new Object[11];
            row[0]=fl;//the object
            row[1]=fl.getFlighttime();
            row[2]=fl.getAirplane().getSerialnumber();
            row[3]=fl.getAirplane().getAvalable();
            row[4]=fl.getAirplane().getManufacturer();
            row[5]=fl.getAirplane().getManufactureyear();
            row[6]=fl.getAirplane().getModelnumber();
            row[7]=fl.getAirplane().getSeatnumber();
            row[8]=fl.getAirplane().getUpdatedate();
            row[9]=fl.getAirplane().getExpired();
            row[10]=fl.getAirplane().getAirliner();
            dtm.addRow(row);
            }
        }
        
        
        
    }//GEN-LAST:event_BtnFindSerialNumActionPerformed

    private void BtnShowExpiredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnShowExpiredActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm=(DefaultTableModel)tblFlight.getModel();
        dtm.setRowCount(0);
       
        
        for(Flight fl:fh.getFlightHistory())
        {
            if(fl.getAirplane().getExpired().equals("YES"))
            {
            Object row[]=new Object[11];
            row[0]=fl;//the object
            row[1]=fl.getFlighttime();
            row[2]=fl.getAirplane().getSerialnumber();
            row[3]=fl.getAirplane().getAvalable();
            row[4]=fl.getAirplane().getManufacturer();
            row[5]=fl.getAirplane().getManufactureyear();
            row[6]=fl.getAirplane().getModelnumber();
            row[7]=fl.getAirplane().getSeatnumber();
            row[8]=fl.getAirplane().getUpdatedate();
            row[9]=fl.getAirplane().getExpired();
            row[10]=fl.getAirplane().getAirliner();
            dtm.addRow(row);
            }
        }
    }//GEN-LAST:event_BtnShowExpiredActionPerformed

    private void AVAILABLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AVAILABLEActionPerformed
        // TODO add your handling code here:
         DefaultTableModel dtm=(DefaultTableModel)tblFlight.getModel();
        dtm.setRowCount(0);
       
        
        for(Flight fl:fh.getFlightHistory())
        {
            if(fl.getAirplane().getAvalable().equals("AVAILABLE")&&fl.getAirport().equals(txtAVAairport.getText()))
            {
            Object row[]=new Object[11];
            row[0]=fl;//the object
            row[1]=fl.getFlighttime();
            row[2]=fl.getAirplane().getSerialnumber();
            row[3]=fl.getAirplane().getAvalable();
            row[4]=fl.getAirplane().getManufacturer();
            row[5]=fl.getAirplane().getManufactureyear();
            row[6]=fl.getAirplane().getModelnumber();
            row[7]=fl.getAirplane().getSeatnumber();
            row[8]=fl.getAirplane().getUpdatedate();
            row[9]=fl.getAirplane().getExpired();
            row[10]=fl.getAirplane().getAirliner();
            dtm.addRow(row);
            }
        }
        
    }//GEN-LAST:event_AVAILABLEActionPerformed

    private void txtAVAairportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAVAairportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAVAairportActionPerformed

    private void txtLastUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastUpdateActionPerformed

    private void BtnLastUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLastUpdateActionPerformed
        // TODO add your handling code here:
        int i;
      Flight fff=(Flight)tblFlight.getValueAt(0, 0);
      Date oridate = fff.getAirplane().getUpdatedate();//to create an oriday
       for(i=0;i<tblFlight.getRowCount();i++)
       {
        Flight fl=(Flight)tblFlight.getValueAt(i, 0);
        Date lastupdatedate = fl.getAirplane().getUpdatedate();
        //get the updatedate from the arraylist 
        // it will refresh everytime
        
        if (lastupdatedate.after(oridate))
        {
            oridate=lastupdatedate;
        }
       }
        DateFormat df = new SimpleDateFormat("MM/dd/yyyy");
        String strupdatedate = df.format(oridate);
       txtLastUpdate.setText(strupdatedate );
       
        
    }//GEN-LAST:event_BtnLastUpdateActionPerformed

    private void BtnAllManufactureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAllManufactureActionPerformed
        // TODO add your handling code here:
        List<String> manus = new ArrayList<String>();
        for(Flight fl:fh.getFlightHistory())
          {  
              if(fl.getAirplane().getAirliner().equals(txtSelectAl.getText()))
              {
                 manus.add(fl.getAirplane().getManufacturer());
              }
          }
        Set<String> uniquemanus = new HashSet<String>(manus);
        
        
        
         //DefaultTableModel dtm=(DefaultTableModel)TblManu.getModel();
        //dtm.setRowCount(0);
        int i;
        /*for(i=0;i<uniquemanus.size();i++)
        {
            Object row[]=new Object[1];
            row[0]=uniquemanus.toString();//the object
            dtm.addRow(row);
            tblShowManus.setText(uniquemanus.toString());
        }*/
        Object[] obj =uniquemanus.toArray();
     
        StringBuilder sb=new StringBuilder();
        
       txtShowManus.setText(Arrays.toString(obj));
        /*for (i=0; i<uniquemanus.size(); i++)
        {
         
        }  */
        
        
        
    }//GEN-LAST:event_BtnAllManufactureActionPerformed

    private void txtSelectAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSelectAlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSelectAlActionPerformed

    private void txtShowManusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShowManusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtShowManusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AVAILABLE;
    private javax.swing.JTextField AVATextField;
    private javax.swing.JTextField AirlinerTextField;
    private javax.swing.JTextField AirportTextField;
    private javax.swing.JButton BtnAVANum;
    private javax.swing.JButton BtnAllManufacture;
    private javax.swing.JButton BtnBoeing;
    private javax.swing.JButton BtnFindSerialNum;
    private javax.swing.JButton BtnFirstAVA;
    private javax.swing.JButton BtnLastUpdate;
    private javax.swing.JButton BtnListGivenYear;
    private javax.swing.JButton BtnSeatNum;
    private javax.swing.JButton BtnShowExpired;
    private javax.swing.JButton BtnViewAll;
    private javax.swing.JTextField EXPTextField;
    private javax.swing.JTextField FlightTimeTextField;
    private javax.swing.JTextField ManuTextField;
    private javax.swing.JTextField ManuYearTextField;
    private javax.swing.JTextField ModelNumTextField;
    private javax.swing.JTextField SearchModelTxt;
    private javax.swing.JTextField SearchSerialTxt;
    private javax.swing.JTextField SeatsTextField;
    private javax.swing.JButton SelectModelNum;
    private javax.swing.JTextField SerialNumTextField;
    private javax.swing.JTextField UDTextField;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFlight;
    private javax.swing.JTextField txtAVA;
    private javax.swing.JTextField txtAVAairport;
    private javax.swing.JTextField txtGivenYear;
    private javax.swing.JTextField txtLastUpdate;
    private javax.swing.JTextField txtMax;
    private javax.swing.JTextField txtMin;
    private javax.swing.JTextField txtNA;
    private javax.swing.JTextField txtSelectAl;
    private javax.swing.JTextField txtShowManus;
    // End of variables declaration//GEN-END:variables
}
